### ISSUE TITLE
正确安装blinker环境后仍无法运行脚本

### ISSUE THREAD

**Issue by Memorywzd** [SodaWithoutSparkles/Blinker_WOL#1]
设备：树莓派4B  环境：docker python:3.8
按照教程安装了需要的库，运行程序时仍提示
Traceback (most recent call last):
  File "Xiaomi_AI_WOL.py", line 15, in <module>
    Blinker.mode("BLINKER_WIFI")
  File "/usr/local/lib/python3.8/site-packages/Blinker-0.2.0-py3.8.egg/Blinker/Blinker.py", line 117, in mode
    import BlinkerAdapters.BlinkerLinuxWS as bWS
  File "/usr/local/lib/python3.8/site-packages/Blinker-0.2.0-py3.8.egg/BlinkerAdapters/__init__.py", line 6, in <module>
    from .BlinkerBLE import *
  File "/usr/local/lib/python3.8/site-packages/Blinker-0.2.0-py3.8.egg/BlinkerAdapters/BlinkerBLE.py", line 7, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

尝试：
apt-get install python-dbus
apt-get install python3-dbus
pip install dbus-python
均无效，上述问题仍存在，求解答

**Comment by SodaWithoutSparkles** [comment]
我是在普通环境下运行没用docker，看看行不行。
如果是code的话可以用github 的markdown：
```
```Code```
```

不好意思没看到通知

试一下不在docker下运行，看看有没有同一个情况。然后试试运行官方支援小爱的程序，看看行不行。


Edit: 看到askububtu上面有另外的[thread](https://askubuntu.com/a/1179505/1045114)也有这个问题，可以参考。有个解决方法是运行一下两段code（不过他是python3.7的，可能要改成python3.8？）:

```
sudo apt-get install python3.7-dev
pip3 install dbus-python
```

再老土的方法也要一试，reboot试过没有？

实际上我也是有这个需求所以尝试在示例东抄西补，也有可能去blinker的[repo](https://github.com/blinker-iot/blinker-py)问会更快

**Comment by Memorywzd** [comment]
谢谢！可能是docker环境下基础环境不完整，精简掉blinker中包含蓝牙"BLE"模块后脚本得以正常执行 感谢提供的解决方案
尝试多次各种方法均无效，可能是由于树莓派刷了openwrt固件导致。相同的模块在本地Ubuntu上可以完美的执行，搬运至树莓派上才产生的各种问题。

**Comment by SodaWithoutSparkles** [comment]
可能是docker里面有些东西联络不上吧。

题外话：如果刷了openwrt的话不如也加上pihole和pivpn吧
@Memorywzd
